### ISSUE TITLE
Versioning of Slides?

### ISSUE THREAD

**Issue by odonnetp** [micmania1/silverstripe-nivoslider#1]
Nivo Slider works great out of the box, but one thing clients want is versioning of each slide, so that they can add a slide to a Slider to publish later. Any thoughts to adding versioning to individual slide elements?

**Comment by micmania1** [comment]
I think rather than versioning it might be better to have a toggle to say whether or not a slide is live.

Through doing this we can check the current stage so we could show 'staged' slides when previewing a site and only show 'live' slides when viewing the live stage.

Also if we went down the versioning route we'd have tables full of unnecessary data as you would never really rollback to an older version like you would with a CMS page.

Thoughts?

**Comment by odonnetp** [comment]
Yeah, that sounds just as fine as well. Could be a checkbox for "Published?". If checked, shows on Live site. If unchecked, shows on Stage site.

**Comment by micmania1** [comment]
I think this functionality should be added on a per-project basis. The reason for this is that any type of object could require this functionality so I don't think its specific to this module.

There are also ways around this. For example you could create a temporary slider and use that until you'd like to publish your updated version.

If you'd like the publish functionality i've created a gist here: https://gist.github.com/micmania1/7876b36af8f267b55485#file-publishextension-php

You can just apply that to NivoSliderSlide as an extension which will give you the functionality you require.

**Comment by odonnetp** [comment]
Thanks! Works great.
